#spring:
#  profiles:
#    active: default

server:
  port: 9091

spring.datasource.tomcat.max-wait: 20000
spring.datasource.tomcat.max-active: 150
spring.datasource.tomcat.max-idle: 20
spring.datasource.tomcat.min-idle: 15

spring.datasource.driver-class-name=: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/Ebbi
spring.datasource.username: ebbi
spring.datasource.password: EbbiService1



spring:
  application.type: angular_2_springboot
  profiles.active: test

logging.level:
  root: INFO
  br.com.embraer.aheadpro: DEBUG
  org.hibernate.orm.deprecation: ERROR

liquibase.change-log: classpath:database/liquibase/db.changelog.xml

ebbi:
  service:
    descriptor:
      name: LarSen EBBi
      description: Energy branding benchmarking index
      serviceTier: CRITICAL
      tags:
        - ebbi-api
        - service

liquibase:
  enabled: true
  contexts: test

---

spring:
  profiles: ebbi-prod-preprod1


---

spring:
  profiles: ebbi-prod-prod1

